CREATE TABLE LIBRARY_USER(
  ID NUMBER PRIMARY KEY,
  USERNAME VARCHAR(32) NOT NULL UNIQUE,
  PASSWORD VARCHAR(16) NOT NULL,
  FIRSTNAME VARCHAR(32) NOT NULL,
  LASTNAME VARCHAR (32) NOT NULL
);

CREATE TABLE BOOK_DATABASE(
  ISBN NUMBER PRIMARY KEY,
  TITLE VARCHAR(64),
  GENRE VARCHAR(16),
  AUTHOR VARCHAR(32),
  NUMBEROFPAGES NUMBER,
  AVAILABILITY VARCHAR(16),
  PUBLISHEDYEAR VARCHAR(16),
  SUMMARY VARCHAR(128)
);

CREATE TABLE RESERVED_BOOK(
  ID NUMBER PRIMARY KEY, 
  BORROWDATE DATE,
  RETURNDATE DATE, 
  OVERDUESTATUS VARCHAR(8),
  OVERDUEFEE NUMBER 
);